name: CI Pipeline

# Déclencher le workflow sur chaque push ou pull request vers la branche principale
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Récupérer le code source
      - name: Checkout repository
        uses: actions/checkout@v3

      # Étape 2 : Configurer Python 3.11
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # Étape 3 : Installer les dépendances
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install colorama pytest

      # Étape 4 : Exécuter les tests unitaires avec pytest
      - name: Run unit tests with pytest
        run: python -m 

     
